version: 0.2

phases:
  pre_build:
    commands:
      - echo "Retrieving environment variables from AWS SSM..."
      - aws ssm get-parameter --name "/trade-bot/.env" --with-decryption --query "Parameter.Value" --output text > .env

      - echo "Retrieving SSH key from AWS SSM..."
      - aws ssm get-parameter --name "/trade-bot/ssh-key" --with-decryption --query "Parameter.Value" --output text > trade-bot-key
      - chmod 600 trade-bot-key

  build:
    commands:
      - echo "Creating tar archive of latest files..."
      - mkdir -p workspace
      - rsync -av --progress ./ workspace/ --exclude '.git' --exclude '*.log' --exclude 'tmp/*'
      - tar -czf trade-bot.tar.gz -C workspace .

      - echo "Transferring latest files to EC2 instance..."
      - scp -o StrictHostKeyChecking=no -i trade-bot-key trade-bot.tar.gz root@51.92.33.198:/root/

      - echo "Transferring .env file to EC2 instance..."
      - scp -o StrictHostKeyChecking=no -i trade-bot-key .env root@51.92.33.198:/root/

      - echo "Cleaning up old files and deploying on EC2..."
      - |
        ssh -o StrictHostKeyChecking=no -i trade-bot-key root@51.92.33.198 << 'EOF'
        echo "Removing all existing files in /root/trade_bot_py..."
        rm -rf /root/trade_bot_py/*

        echo "Extracting new files..."
        mkdir -p /root/trade_bot_py
        mv /root/trade-bot.tar.gz /root/trade_bot_py/
        cd /root/trade_bot_py
        tar -xzf trade-bot.tar.gz
        rm -f trade-bot.tar.gz

        echo "Setting up environment..."
        mv /root/.env /root/trade_bot_py/.env  

        echo "Deploying with Docker..."
        docker-compose down --remove-orphans
        docker-compose up -d --build
        docker system prune -af --volumes
        EOF

      - echo "Cleaning up private key..."
      - rm -f trade-bot-key

artifacts:
  files:
    - "**/*"
