version: 0.2

phases:
  pre_build:
    commands:
      - echo "Retrieving environment variables from AWS SSM..."
      - aws ssm get-parameter --name "/trade-bot/.env" --with-decryption --query "Parameter.Value" --output text > .env

      - echo "Retrieving SSH key from AWS SSM..."
      - aws ssm get-parameter --name "/trade-bot/ssh-key" --with-decryption --query "Parameter.Value" --output text > trade-bot-key
      - chmod 600 trade-bot-key

  build:
    commands:
      - echo "Deploying code to EC2 instance..."
      - tar -czf trade-bot.tar.gz . 
      - scp -o StrictHostKeyChecking=no -i trade-bot-key trade-bot.tar.gz root@51.92.33.198:/home/root/
      - |
        ssh -o StrictHostKeyChecking=no -i trade-bot-key root@51.92.33.198 << 'EOF'
        cd /home/root
        tar -xzf trade-bot.tar.gz
        rm -f trade-bot.tar.gz
        mv .env /home/root/trade_bot_py/.env  
        cd /home/root/trade_bot_py
        docker-compose down --remove-orphans
        docker-compose up -d --build
        docker system prune -af --volumes
        EOF

artifacts:
  files:
    - "**/*"
